"""empty message

Revision ID: 48dd87344140
Revises: 
Create Date: 2021-07-02 12:00:09.784901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dd87344140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.Column('name_place', sa.String(), nullable=True),
    sa.Column('lon', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_place')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
